In [28]:
import numpy as np

In [35]:
x=np.array([10,20,30,40,50,60,70,80,90,100])
print 'Type:',type(x)
print 'Content:',x
print 'Length:',len(x)
print 'Dimension',x.shape
print '5th Index Element',x[5]
print 'Range:',x[0:5]

Type: <type 'numpy.ndarray'>
Content: [ 10  20  30  40  50  60  70  80  90 100]
Length: 10
Dimension (10L,)
5th Index Element 60
Range: [10 20 30 40]


In [73]:
x=np.array([(10,20,30),(40,50,60),[70,80,90]])

y=np.array([(10,20,30),(40,50,60),[70,80,90]])
z=x*y
print z[[0,2]]
print y.shape
print 'Type of element: ',y.dtype
print y[2][2]
print y[[0,2]]
print 'Reverese of matrix',y[::-1]
print 50 in y
print len(y)


a=np.array([1,2])
b=np.array([[2],[1]])
c=a*b
print a
print b
print c

[[ 100  400  900]
 [4900 6400 8100]]
(3L, 3L)
Type of element:  int32
90
[[10 20 30]
 [70 80 90]]
Reverese of matrix [[70 80 90]
 [40 50 60]
 [10 20 30]]
True
3
[1 2]
[[2]
 [1]]
[[2 4]
 [1 2]]


In [84]:
#Arrays using Range function

z=np.array(range(10,100,10))
print z
print type(z)
print z.shape
z1=z.reshape(3,3)
print z1
print z1.flatten()


[10 20 30 40 50 60 70 80 90]
<type 'numpy.ndarray'>
(9L,)
[[10 20 30]
 [40 50 60]
 [70 80 90]]
[10 20 30 40 50 60 70 80 90]
[5, 6, 7, 8, 9, 10]


In [107]:
x=np.arange(1.0,10.0,0.5,dtype=float)
print 'Type of Object: ',type(x)
print 'No. of elements in Object',x.size
print 'Total Size of x:',x.nbytes
print 'Element size:',x.itemsize
print x.reshape(2,9)
print x+1

Type of Object:  <type 'numpy.ndarray'>
No. of elements in Object 18
Total Size of x: 144
Element size: 8
[[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
 [5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]]
[ 2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5  8.   8.5
  9.   9.5 10.  10.5]


In [122]:
x=np.array(range(1,10,1))
y=np.array([1,2,3])
print x
print y
print x+1
print x*2
z=x.reshape(3,3)
c=z*y
print c
print x

[1 2 3 4 5 6 7 8 9]
[1 2 3]
[ 2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10 12 14 16 18]
[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]
[1 2 3 4 5 6 7 8 9]


In [135]:
x=np.array([[1,2,3,4],[1,2,3,4]])
print x.shape
y=np.array([[1,2],[3,4],[1,2],[3,4]])
print y.shape
print x
print y

x=x.reshape(2,4)
y=y.reshape(4,2)
print x
print y



(2L, 4L)
(4L, 2L)
[[1 2 3 4]
 [1 2 3 4]]
[[1 2]
 [3 4]
 [1 2]
 [3 4]]
[[1 2 3 4]
 [1 2 3 4]]
[[1 2]
 [3 4]
 [1 2]
 [3 4]]


In [160]:
#Array Traversing
x=np.array(range(10,100,10))
print x
y=x.reshape(3,3)
print y
print y[1,2]
print x[[1,2]]
print '\nSlice Array from index x[1:] till end: \n',y[1:]
print 'Items in second column',y[...,1]
print 'items in second row',y[1,...]
print 'items in second row',y[1]
print 'items in second till last row\n',y[1:,...]
print 'items found in column 1 onwards are \n', y[...,1:]



[10 20 30 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]]
60
[20 30]

Slice Array from index x[1:] till end: 
[[40 50 60]
 [70 80 90]]
Items in second column [20 50 80]
items in second row [40 50 60]
items in second row [40 50 60]
items in second till last row
[[40 50 60]
 [70 80 90]]
items found in column 1 onwards are 
[[20 30]
 [50 60]
 [80 90]]


In [168]:
x=np.array([[10,20,30],[40,50,60],[70,80,90]])
print x
bool_index=x>50
print bool_index
print x[bool_index]
print x[x<50]
print "Fill with 1s",np.ones((3,3),dtype=np.int32)
print "Fill with 0s",np.zeros((3,3),dtype=np.int32)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[False False False]
 [False False  True]
 [ True  True  True]]
[60 70 80 90]
[10 20 30 40]
Fill with 1s [[1 1 1]
 [1 1 1]
 [1 1 1]]
Fill with 0s [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [175]:
x=np.array([[10,20,30],[40,50,60],[70,80,90]])
y=np.array([[10,20,30],[40,50,60],[70,80,90]])

print np.add(x,y)
print np.subtract(x,y)
print np.multiply(x,y)
print np.divide(x,y)

x=np.array(range(1,5,1))
print x
print x.reshape(2,2)


[[ 20  40  60]
 [ 80 100 120]
 [140 160 180]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 100  400  900]
 [1600 2500 3600]
 [4900 6400 8100]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[1 2 3 4]
[[1 2]
 [3 4]]


In [184]:
print np.sort(y,axis=1)
print 'Flatens arrays',np.sort(y, axis=None)
print 'Sort Array along first axis i.e columns',np.sort(y,axis=0)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
Flatens arrays [10 20 30 40 50 60 70 80 90]
Sort Array along first axis i.e columns [[10 20 30]
 [40 50 60]
 [70 80 90]]


In [192]:
x=np.array([1,2,3,4,5,6,7,8,9])
print x[3],x[5]
fancy_index=[3,5,7]
print 'Elements of index 3,5,7 are',x[fancy_index]
print 'Selective Values of Array',y[[0,2],[2,0]]

4 6
Elements of index 3,5,7 are [4 6 8]
Selective Values of Array [30 70]


In [197]:
x=np.array(np.arange(1,41)).reshape(8,5)
print x


 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]]


In [228]:
x=np.arange(10,100,10,dtype=np.int32).reshape((3,3))
print x

y=transpose(x)
print y

#print 'Swapaxes: ',np.swapaxes(x,0,1)
print 'Swapaxes: \n',np.swapaxes(x,0,1)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[10 40 70]
 [20 50 80]
 [30 60 90]]
Swapaxes: 
[[10 40 70]
 [20 50 80]
 [30 60 90]]


In [234]:
linvalue=np.linspace(1,5)
#By default num=50, endPoint=Last value should we consider or not
print linvalue

linvalue=np.linspace(10,50,num=10,dtype=np.int64)#,endpoint=True)
#By default num=50, endPoint=Last value should we consider or not
print linvalue

[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]
[10 14 18 23 27 32 36 41 45 50]


In [242]:
x=np.random.random((3,3))
print x
print np.max(x,axis=0) #Axis 0 = Column Axis 1= ROw
print np.min(x,axis=0) #Axis 0 = Column Axis 1= ROw

[[0.67192748 0.54800641 0.91652192]
 [0.76587589 0.72325531 0.43731603]
 [0.79082442 0.22821533 0.19378702]]
[0.79082442 0.72325531 0.91652192]
[0.67192748 0.22821533 0.19378702]
